package uk.ac.ed.acp4.ticket;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.amqp.rabbit.annotation.RabbitListener;
import org.springframework.stereotype.Service;
import uk.ac.ed.acp4.github.GitHubService;
import uk.ac.ed.acp4.model.AgentResponse;
import uk.ac.ed.acp4.model.AuditLog;
import uk.ac.ed.acp4.model.CodeFix;
import uk.ac.ed.acp4.model.Ticket;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

@Service
public class TicketService {

    private static final Logger log = LoggerFactory.getLogger(TicketService.class);

    private final TicketRepository ticketRepository;
    private final CodeFixRepository codeFixRepository;
    private final AuditLogRepository auditLogRepository;
    private final GitHubService gitHubService;
    private final ObjectMapper objectMapper = new ObjectMapper();

    public TicketService(TicketRepository ticketRepository,
                         CodeFixRepository codeFixRepository,
                         AuditLogRepository auditLogRepository,
                         GitHubService gitHubService) {
        this.ticketRepository = ticketRepository;
        this.codeFixRepository = codeFixRepository;
        this.auditLogRepository = auditLogRepository;
        this.gitHubService = gitHubService;
    }

    @RabbitListener(queues = "${app.rabbitmq.queue}")
    public void handleAgentResponse(String message) {
        try {
            AgentResponse response = objectMapper.readValue(message, AgentResponse.class);
            createTicketFromResponse(response);
        } catch (Exception e) {
            log.error("Failed to process RabbitMQ message: {}", e.getMessage());
        }
    }

    public Ticket createTicketFromResponse(AgentResponse response) {
        Ticket ticket = new Ticket();
        ticket.setServiceName(response.getServiceName());
        ticket.setProblem(response.getProblem());
        ticket.setRootCause(response.getRootCause());
        ticket.setSeverity(response.getSeverity());
        ticket.setFixType(response.getFixType() != null ? response.getFixType() : "INVESTIGATION");
        ticket.setRecommendedFix(response.getRecommendedFix());
        ticket.setEta(response.getEta());
        ticket.setAffectedUsers(response.getAffectedUsers());
        ticket.setStatus("OPEN");
        ticket = ticketRepository.save(ticket);
        log.info("Ticket #{} created for {} — fixType: {}", ticket.getId(), ticket.getServiceName(), ticket.getFixType());

        // Only save code fix if it's actually a code change
        if ("CODE_CHANGE".equals(response.getFixType()) &&
                response.getCodePatch() != null && !response.getCodePatch().isBlank()) {
            CodeFix fix = new CodeFix();
            fix.setTicketId(ticket.getId());
            fix.setFilePath(response.getCodeFilePath());
            fix.setPatch(response.getCodePatch());
            fix.setExplanation(response.getCodeExplanation());
            fix.setStatus("PENDING");
            codeFixRepository.save(fix);
            log.info("Code fix saved for ticket #{}", ticket.getId());
        }

        AuditLog audit = new AuditLog();
        audit.setTicketId(ticket.getId());
        audit.setAction("CREATED");
        audit.setPerformedBy("system");
        audit.setNotes("Auto-generated by AI agent. Fix type: " + ticket.getFixType());
        auditLogRepository.save(audit);

        return ticket;
    }

    public Ticket approveTicket(Long ticketId, String engineer) {
        Ticket ticket = ticketRepository.findById(ticketId)
                .orElseThrow(() -> new RuntimeException("Ticket not found: " + ticketId));

        ticket.setStatus("APPROVED");
        ticket.setUpdatedAt(LocalDateTime.now());
        ticketRepository.save(ticket);

        // Only open a GitHub PR if this is a code change
        if ("CODE_CHANGE".equals(ticket.getFixType())) {
            codeFixRepository.findByTicketId(ticketId).ifPresent(fix -> {
                fix.setStatus("APPROVED");
                fix.setUpdatedAt(LocalDateTime.now());
                codeFixRepository.save(fix);

                String prUrl = gitHubService.createFixPullRequest(
                        ticketId,
                        ticket.getServiceName(),
                        fix.getFilePath(),
                        fix.getPatch(),
                        ticket.getProblem(),
                        fix.getExplanation()
                );

                if (prUrl != null) {
                    ticket.setPrUrl(prUrl);
                    ticketRepository.save(ticket);

                    AuditLog prAudit = new AuditLog();
                    prAudit.setTicketId(ticketId);
                    prAudit.setAction("PR_OPENED");
                    prAudit.setPerformedBy("system");
                    prAudit.setNotes("Pull request opened: " + prUrl);
                    auditLogRepository.save(prAudit);
                    log.info("PR created for ticket #{}: {}", ticketId, prUrl);
                }
            });
        } else {
            // For non-code fixes, just log the approval action
            log.info("Ticket #{} approved ({}). No PR needed — action: {}",
                    ticketId, ticket.getFixType(), ticket.getRecommendedFix());
        }

        AuditLog audit = new AuditLog();
        audit.setTicketId(ticketId);
        audit.setAction("APPROVED");
        audit.setPerformedBy(engineer);
        audit.setNotes(buildApprovalNote(ticket));
        auditLogRepository.save(audit);

        log.info("Ticket #{} approved by {}", ticketId, engineer);
        return ticket;
    }

    private String buildApprovalNote(Ticket ticket) {
        return switch (ticket.getFixType() != null ? ticket.getFixType() : "INVESTIGATION") {
            case "CODE_CHANGE"   -> "Approved — PR opened on GitHub for staging review";
            case "CONFIG_CHANGE" -> "Approved — configuration change to be applied by ops team";
            case "DB_OPERATION"  -> "Approved — database operation queued for DBA review";
            case "EXTERNAL"      -> "Approved — escalated to third-party vendor";
            default              -> "Approved — assigned for manual investigation";
        };
    }

    public Ticket rejectTicket(Long ticketId, String engineer, String reason) {
        Ticket ticket = ticketRepository.findById(ticketId)
                .orElseThrow(() -> new RuntimeException("Ticket not found: " + ticketId));

        ticket.setStatus("REJECTED");
        ticket.setUpdatedAt(LocalDateTime.now());
        ticketRepository.save(ticket);

        codeFixRepository.findByTicketId(ticketId).ifPresent(fix -> {
            fix.setStatus("REJECTED");
            fix.setUpdatedAt(LocalDateTime.now());
            codeFixRepository.save(fix);
        });

        AuditLog audit = new AuditLog();
        audit.setTicketId(ticketId);
        audit.setAction("REJECTED");
        audit.setPerformedBy(engineer);
        audit.setNotes(reason);
        auditLogRepository.save(audit);

        log.info("Ticket #{} rejected by {}: {}", ticketId, engineer, reason);
        return ticket;
    }

    public List<Ticket> getAllTickets()                      { return ticketRepository.findAll(); }
    public List<Ticket> getTicketsByStatus(String status)   { return ticketRepository.findByStatus(status); }
    public Optional<Ticket> getTicketById(Long id)          { return ticketRepository.findById(id); }
    public Optional<CodeFix> getCodeFixByTicketId(Long id)  { return codeFixRepository.findByTicketId(id); }
    public List<AuditLog> getAuditLog(Long ticketId)        { return auditLogRepository.findByTicketIdOrderByCreatedAtDesc(ticketId); }
}