package uk.ac.ed.acp4.ticket;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.amqp.rabbit.annotation.RabbitListener;
import org.springframework.stereotype.Service;
import uk.ac.ed.acp4.model.AgentResponse;
import uk.ac.ed.acp4.model.AuditLog;
import uk.ac.ed.acp4.model.CodeFix;
import uk.ac.ed.acp4.model.Ticket;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

@Service
public class TicketService {

    private static final Logger log = LoggerFactory.getLogger(TicketService.class);

    private final TicketRepository ticketRepository;
    private final CodeFixRepository codeFixRepository;
    private final AuditLogRepository auditLogRepository;
    private final ObjectMapper objectMapper = new ObjectMapper();

    public TicketService(TicketRepository ticketRepository,
                         CodeFixRepository codeFixRepository,
                         AuditLogRepository auditLogRepository) {
        this.ticketRepository = ticketRepository;
        this.codeFixRepository = codeFixRepository;
        this.auditLogRepository = auditLogRepository;
    }

    @RabbitListener(queues = "${app.rabbitmq.queue}")
    public void handleAgentResponse(String message) {
        try {
            AgentResponse response = objectMapper.readValue(message, AgentResponse.class);
            createTicketFromResponse(response);
        } catch (Exception e) {
            log.error("Failed to process RabbitMQ message: {}", e.getMessage());
        }
    }

    public Ticket createTicketFromResponse(AgentResponse response) {
        Ticket ticket = new Ticket();
        ticket.setServiceName(response.getServiceName());
        ticket.setProblem(response.getProblem());
        ticket.setRootCause(response.getRootCause());
        ticket.setSeverity(response.getSeverity());
        ticket.setRecommendedFix(response.getRecommendedFix());
        ticket.setEta(response.getEta());
        ticket.setAffectedUsers(response.getAffectedUsers());
        ticket.setStatus("OPEN");
        ticket = ticketRepository.save(ticket);
        log.info("Ticket #{} created for service: {}", ticket.getId(), ticket.getServiceName());

        if (response.getCodePatch() != null && !response.getCodePatch().isBlank()) {
            CodeFix fix = new CodeFix();
            fix.setTicketId(ticket.getId());
            fix.setFilePath(response.getCodeFilePath());
            fix.setPatch(response.getCodePatch());
            fix.setExplanation(response.getCodeExplanation());
            fix.setStatus("PENDING");
            codeFixRepository.save(fix);
            log.info("Code fix saved for ticket #{}", ticket.getId());
        }

        AuditLog audit = new AuditLog();
        audit.setTicketId(ticket.getId());
        audit.setAction("CREATED");
        audit.setPerformedBy("system");
        audit.setNotes("Auto-generated by AI agent");
        auditLogRepository.save(audit);

        return ticket;
    }

    public Ticket approveTicket(Long ticketId, String engineer) {
        Ticket ticket = ticketRepository.findById(ticketId)
                .orElseThrow(() -> new RuntimeException("Ticket not found: " + ticketId));
        ticket.setStatus("APPROVED");
        ticket.setUpdatedAt(LocalDateTime.now());
        ticketRepository.save(ticket);

        codeFixRepository.findByTicketId(ticketId).ifPresent(fix -> {
            fix.setStatus("APPROVED");
            fix.setUpdatedAt(LocalDateTime.now());
            codeFixRepository.save(fix);
            log.info("Code fix approved for ticket #{} — ready for staging", ticketId);
        });

        AuditLog audit = new AuditLog();
        audit.setTicketId(ticketId);
        audit.setAction("APPROVED");
        audit.setPerformedBy(engineer);
        audit.setNotes("Approved and queued for non-prod deployment");
        auditLogRepository.save(audit);

        log.info("Ticket #{} approved by {}", ticketId, engineer);
        return ticket;
    }

    public Ticket rejectTicket(Long ticketId, String engineer, String reason) {
        Ticket ticket = ticketRepository.findById(ticketId)
                .orElseThrow(() -> new RuntimeException("Ticket not found: " + ticketId));
        ticket.setStatus("REJECTED");
        ticket.setUpdatedAt(LocalDateTime.now());
        ticketRepository.save(ticket);

        codeFixRepository.findByTicketId(ticketId).ifPresent(fix -> {
            fix.setStatus("REJECTED");
            fix.setUpdatedAt(LocalDateTime.now());
            codeFixRepository.save(fix);
        });

        AuditLog audit = new AuditLog();
        audit.setTicketId(ticketId);
        audit.setAction("REJECTED");
        audit.setPerformedBy(engineer);
        audit.setNotes(reason);
        auditLogRepository.save(audit);

        log.info("Ticket #{} rejected by {}: {}", ticketId, engineer, reason);
        return ticket;
    }

    public List<Ticket> getAllTickets() { return ticketRepository.findAll(); }

    public List<Ticket> getTicketsByStatus(String status) { return ticketRepository.findByStatus(status); }

    public Optional<Ticket> getTicketById(Long id) { return ticketRepository.findById(id); }

    public Optional<CodeFix> getCodeFixByTicketId(Long ticketId) { return codeFixRepository.findByTicketId(ticketId); }

    public List<AuditLog> getAuditLog(Long ticketId) { return auditLogRepository.findByTicketIdOrderByCreatedAtDesc(ticketId); }
}