package uk.ac.ed.acp4.ticket;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.amqp.rabbit.annotation.RabbitListener;
import org.springframework.stereotype.Service;
import uk.ac.ed.acp4.github.GitHubService;
import uk.ac.ed.acp4.model.AgentResponse;
import uk.ac.ed.acp4.model.AuditLog;
import uk.ac.ed.acp4.model.CodeFix;
import uk.ac.ed.acp4.model.SqlFix;
import uk.ac.ed.acp4.model.Ticket;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;

@Service
public class TicketService {

    private static final Logger log = LoggerFactory.getLogger(TicketService.class);

    private final TicketRepository ticketRepository;
    private final CodeFixRepository codeFixRepository;
    private final SqlFixRepository sqlFixRepository;
    private final AuditLogRepository auditLogRepository;
    private final GitHubService gitHubService;
    private final SqlExecutionService sqlExecutionService;
    private final EmailService emailService;
    private final ObjectMapper objectMapper = new ObjectMapper();

    public TicketService(TicketRepository ticketRepository,
                         CodeFixRepository codeFixRepository,
                         SqlFixRepository sqlFixRepository,
                         AuditLogRepository auditLogRepository,
                         GitHubService gitHubService,
                         SqlExecutionService sqlExecutionService,
                         EmailService emailService) {
        this.ticketRepository    = ticketRepository;
        this.codeFixRepository   = codeFixRepository;
        this.sqlFixRepository    = sqlFixRepository;
        this.auditLogRepository  = auditLogRepository;
        this.gitHubService       = gitHubService;
        this.sqlExecutionService = sqlExecutionService;
        this.emailService        = emailService;
    }

    @RabbitListener(queues = "${app.rabbitmq.queue}")
    public void handleAgentResponse(String message) {
        try {
            AgentResponse response = objectMapper.readValue(message, AgentResponse.class);
            createTicketFromResponse(response);
        } catch (Exception e) {
            log.error("Failed to process RabbitMQ message: {}", e.getMessage());
        }
    }

    public Ticket createTicketFromResponse(AgentResponse response) {
        Ticket ticket = new Ticket();
        ticket.setServiceName(response.getServiceName());
        ticket.setProblem(response.getProblem());
        ticket.setRootCause(response.getRootCause());
        ticket.setSeverity(response.getSeverity());
        ticket.setFixType(response.getFixType() != null ? response.getFixType() : "INVESTIGATION");
        ticket.setRecommendedFix(response.getRecommendedFix());
        ticket.setEta(response.getEta());
        ticket.setAffectedUsers(response.getAffectedUsers());
        ticket.setExternalVendor(response.getExternalVendor());
        ticket.setStatus("OPEN");
        ticket = ticketRepository.save(ticket);
        log.info("Ticket #{} created for {} — fixType: {} vendor: {}",
                ticket.getId(), ticket.getServiceName(),
                ticket.getFixType(), ticket.getExternalVendor());

        // Save code fix
        if ("CODE_CHANGE".equals(response.getFixType()) &&
                response.getCodePatch() != null && !response.getCodePatch().isBlank()) {
            CodeFix fix = new CodeFix();
            fix.setTicketId(ticket.getId());
            fix.setFilePath(response.getCodeFilePath());
            fix.setPatch(response.getCodePatch());
            fix.setExplanation(response.getCodeExplanation());
            fix.setStatus("PENDING");
            codeFixRepository.save(fix);
        }

        // Save SQL fix
        if ("DB_OPERATION".equals(response.getFixType()) &&
                response.getSqlScript() != null && !response.getSqlScript().isBlank()) {
            SqlFix sqlFix = new SqlFix();
            sqlFix.setTicketId(ticket.getId());
            sqlFix.setSqlScript(response.getSqlScript());
            sqlFix.setExplanation(response.getSqlExplanation() != null
                    ? response.getSqlExplanation() : "AI-generated SQL fix");
            sqlFix.setStatus("PENDING");
            sqlFixRepository.save(sqlFix);
        }

        AuditLog audit = new AuditLog();
        audit.setTicketId(ticket.getId());
        audit.setAction("CREATED");
        audit.setPerformedBy("system");
        audit.setNotes("Auto-generated by AI agent. Fix type: " + ticket.getFixType());
        auditLogRepository.save(audit);

        return ticket;
    }

    public Optional<Ticket> findOpenTicketByService(String serviceName, String fixType) {
        return ticketRepository
                .findFirstByServiceNameAndStatusAndFixTypeOrderByCreatedAtDesc(
                        serviceName, "OPEN", fixType);
    }

    public void appendAffectedUsers(Long ticketId, List<String> newUserIds) {
        ticketRepository.findById(ticketId).ifPresent(ticket -> {
            Set<String> existing = new LinkedHashSet<>();
            if (ticket.getAffectedUsers() != null && !ticket.getAffectedUsers().isBlank()) {
                Arrays.stream(ticket.getAffectedUsers().split(","))
                        .map(String::trim).filter(s -> !s.isBlank())
                        .forEach(existing::add);
            }
            int before = existing.size();
            existing.addAll(newUserIds);
            int added = existing.size() - before;
            if (added == 0) return;

            ticket.setAffectedUsers(String.join(", ", existing));
            ticket.setUpdatedAt(LocalDateTime.now());
            ticketRepository.save(ticket);

            AuditLog audit = new AuditLog();
            audit.setTicketId(ticketId);
            audit.setAction("USERS_APPENDED");
            audit.setPerformedBy("system");
            audit.setNotes(added + " new user(s) added: " + String.join(", ", newUserIds));
            auditLogRepository.save(audit);

            log.info("Ticket #{} — {} new user(s) appended. Total: {}",
                    ticketId, added, existing.size());
        });
    }

    public Ticket approveTicket(Long ticketId, String engineer) {
        Ticket ticket = ticketRepository.findById(ticketId)
                .orElseThrow(() -> new RuntimeException("Ticket not found: " + ticketId));

        ticket.setStatus("APPROVED");
        ticket.setUpdatedAt(LocalDateTime.now());
        ticketRepository.save(ticket);

        switch (ticket.getFixType() != null ? ticket.getFixType() : "INVESTIGATION") {

            case "CODE_CHANGE" -> codeFixRepository.findByTicketId(ticketId).ifPresent(fix -> {
                fix.setStatus("APPROVED");
                fix.setUpdatedAt(LocalDateTime.now());
                codeFixRepository.save(fix);

                String prUrl = gitHubService.createFixPullRequest(
                        ticketId, ticket.getServiceName(),
                        fix.getFilePath(), fix.getPatch(),
                        ticket.getProblem(), fix.getExplanation());

                if (prUrl != null) {
                    ticket.setPrUrl(prUrl);
                    ticketRepository.save(ticket);

                    AuditLog a = new AuditLog();
                    a.setTicketId(ticketId); a.setAction("PR_OPENED");
                    a.setPerformedBy("system");
                    a.setNotes("Pull request opened: " + prUrl);
                    auditLogRepository.save(a);
                }
            });

            case "DB_OPERATION" -> sqlFixRepository.findByTicketId(ticketId).ifPresent(sqlFix -> {
                SqlExecutionService.SqlExecutionResult result =
                        sqlExecutionService.execute(sqlFix.getSqlScript());

                sqlFix.setStatus(result.isSuccess() ? "EXECUTED" : "FAILED");
                sqlFix.setResult(result.getMessage());
                sqlFix.setExecutedAt(LocalDateTime.now());
                sqlFixRepository.save(sqlFix);

                AuditLog a = new AuditLog();
                a.setTicketId(ticketId);
                a.setAction(result.isSuccess() ? "SQL_EXECUTED" : "SQL_FAILED");
                a.setPerformedBy(engineer);
                a.setNotes(result.getMessage());
                auditLogRepository.save(a);
            });

            case "EXTERNAL" -> {
                String vendorName = ticket.getExternalVendor() != null
                        ? ticket.getExternalVendor() : "external vendor";
                try {
                    String sentTo = emailService.sendVendorEscalation(ticket, engineer);

                    AuditLog a = new AuditLog();
                    a.setTicketId(ticketId);
                    a.setAction("EMAIL_SENT");
                    a.setPerformedBy(engineer);
                    a.setNotes("Vendor escalation email sent to " + vendorName + " <" + sentTo + ">");
                    auditLogRepository.save(a);

                    log.info("Ticket #{} — email sent to {} for vendor {}",
                            ticketId, sentTo, vendorName);
                } catch (Exception e) {
                    AuditLog a = new AuditLog();
                    a.setTicketId(ticketId);
                    a.setAction("EMAIL_FAILED");
                    a.setPerformedBy(engineer);
                    a.setNotes("Failed to send email to " + vendorName + ": " + e.getMessage());
                    auditLogRepository.save(a);

                    log.error("Email failed for ticket #{}: {}", ticketId, e.getMessage());
                }
            }

            default -> log.info("Ticket #{} approved ({}). Manual action required.",
                    ticketId, ticket.getFixType());
        }

        AuditLog audit = new AuditLog();
        audit.setTicketId(ticketId);
        audit.setAction("APPROVED");
        audit.setPerformedBy(engineer);
        audit.setNotes(buildApprovalNote(ticket));
        auditLogRepository.save(audit);

        log.info("Ticket #{} approved by {}", ticketId, engineer);
        return ticket;
    }

    private String buildApprovalNote(Ticket ticket) {
        return switch (ticket.getFixType() != null ? ticket.getFixType() : "INVESTIGATION") {
            case "CODE_CHANGE"   -> "Approved — PR opened on GitHub for staging review";
            case "CONFIG_CHANGE" -> "Approved — configuration change to be applied by ops team";
            case "DB_OPERATION"  -> "Approved — SQL script executed against database";
            case "EXTERNAL"      -> "Approved — vendor escalation email sent automatically";
            default              -> "Approved — assigned for manual investigation";
        };
    }

    public Ticket rejectTicket(Long ticketId, String engineer, String reason) {
        Ticket ticket = ticketRepository.findById(ticketId)
                .orElseThrow(() -> new RuntimeException("Ticket not found: " + ticketId));

        ticket.setStatus("REJECTED");
        ticket.setUpdatedAt(LocalDateTime.now());
        ticketRepository.save(ticket);

        codeFixRepository.findByTicketId(ticketId).ifPresent(fix -> {
            fix.setStatus("REJECTED"); fix.setUpdatedAt(LocalDateTime.now());
            codeFixRepository.save(fix);
        });
        sqlFixRepository.findByTicketId(ticketId).ifPresent(fix -> {
            fix.setStatus("REJECTED"); sqlFixRepository.save(fix);
        });

        AuditLog audit = new AuditLog();
        audit.setTicketId(ticketId); audit.setAction("REJECTED");
        audit.setPerformedBy(engineer); audit.setNotes(reason);
        auditLogRepository.save(audit);

        log.info("Ticket #{} rejected by {}: {}", ticketId, engineer, reason);
        return ticket;
    }

    public List<Ticket> getAllTickets()                      { return ticketRepository.findAll(); }
    public List<Ticket> getTicketsByStatus(String status)   { return ticketRepository.findByStatus(status); }
    public Optional<Ticket> getTicketById(Long id)          { return ticketRepository.findById(id); }
    public Optional<CodeFix> getCodeFixByTicketId(Long id)  { return codeFixRepository.findByTicketId(id); }
    public Optional<SqlFix> getSqlFixByTicketId(Long id)    { return sqlFixRepository.findByTicketId(id); }
    public List<AuditLog> getAuditLog(Long ticketId)        { return auditLogRepository.findByTicketIdOrderByCreatedAtDesc(ticketId); }
}